### ISSUE TITLE
Add strawman forecaster

### ISSUE THREAD

**Issue by jsharpna** [cmu-delphi/covid-19-forecast#2]
In order to test the pipeline, let's add a simple forecaster such as the 
- [strawman](https://github.com/cmu-delphi/covidcast-forecast/tree/main/forecaster_pkgs/strawman)
- [Ryan's simple forecaster](https://delphi.cmu.edu/blog/2020/09/21/can-symptoms-surveys-improve-covid-19-forecasts)

**Comment by dajmcdon** [comment]
Done.
