### ISSUE TITLE
Ensure automatic checks pass for forecaster publishing

### ISSUE THREAD

**Issue by jsharpna** [cmu-delphi/covid-19-forecast#4]

**Comment by dajmcdon** [comment]
This can implemented locally through Rstudio, but better is gh-actions (see https://www.maxheld.de/ghactions/index.html and https://www.jimhester.com/talk/2020-rsc-github-actions/). This is just Github Continuous Integration, and will run some checks on push.

**Comment by dajmcdon** [comment]
I'll take a look shortly. Stuck on Teaching Duties for the moment...

**Comment by dajmcdon** [comment]
This is done. See also #7
