### ISSUE TITLE
Rename zyzzyva files

### ISSUE THREAD

**Issue by sgsmob** [cmu-delphi/covid-19-forecast#40]
The `zyzzyva` file names don't always capture what is going on in the code.  Particular examples:

* `main.R` is not the top-level function (that would be `get_forecasters.R`)
* `data_structures.R` contains modeling parameters and not any custom data structures in the traditional sense
*

**Comment by sarah-colq** [comment]
I can't assign this to myself, but I am assigning it to myself.

**Comment by sarah-colq** [comment]
Thanks @sgsmob !

**Comment by sgsmob** [comment]
Warning that #47 may cause some headaches for merging this

**Comment by sarah-colq** [comment]
This is done, I can't close, can you close @sgsmob ?
