### ISSUE TITLE
Problem running `aardvark`, related to `geo_type`

### ISSUE THREAD

**Issue by bnaras** [cmu-delphi/covid-19-forecast#49]
It appears that the `geo_type`  argument is not handled appropriately. Attached are two runs using and not using `geo_type` argument. I also include the script.

[aadrvark_run.zip](https://github.com/cmu-delphi/covid-19-forecast/files/5934012/aadrvark_run.zip)

**Comment by dajmcdon** [comment]
@capolitsch

**Comment by capolitsch** [comment]
@bnaras @dajmcdon thanks. will debug today.

**Comment by capolitsch** [comment]
@bnaras @dajmcdon Should be good to go now. Closing this issue and reopening the pull request.
